baseURL = "https://poinsla.xyz/"
languageCode = "en-us"
title = "Poinsla"
paginate = 5

[params]
	dateFormat = "2 Jan, 2006 | 3:04pm"
	copyright = "Copyright &copy; 2020 - 2021 [Poinsla.com](https://poinsla.com) All Rights Reserved"